structure(list(alloy_id = character(0), individual_key = structure(numeric(0), class = "integer64"), 
    first_name = character(0), middle_name = character(0), last_name = character(0), 
    suffix = character(0), race = character(0), birth_date = character(0), 
    gender = character(0), ethnicity = character(0), registration_state = character(0), 
    is_deceased = logical(0), graphite_address_id = character(0), 
    graphite_address_type = character(0), graphite_raw_address1 = character(0), 
    graphite_raw_address2 = character(0), graphite_raw_address3 = character(0), 
    graphite_raw_city = character(0), graphite_raw_state = character(0), 
    graphite_raw_zip = structure(numeric(0), class = "integer64"), 
    graphite_raw_zip_suffix = character(0), graphite_raw_country = character(0), 
    graphite_address_number = character(0), graphite_address_predirection = character(0), 
    graphite_address_street = character(0), graphite_address_postdirection = character(0), 
    graphite_address_street_suffix = character(0), graphite_address_secondary_number = character(0), 
    graphite_address_secondary_designator = character(0), graphite_address_extra_secondary_number = character(0), 
    graphite_address_extra_secondary_designator = character(0), 
    graphite_address_pmb_number = character(0), graphite_address_city_name = character(0), 
    graphite_address_state = character(0), graphite_address_zipcode = character(0), 
    graphite_address_plus4_code = character(0)), class = "data.frame", row.names = c(NA, 
0L))
