on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          system("sudo apt-get install -y libcurl4-openssl-dev")
          install.packages(c("remotes", "rcmdcheck"), repos = "https://packagemanager.rstudio.com/all/__linux__/bionic/latest")
          remotes::install_deps(dependencies = TRUE, repos = "https://packagemanager.rstudio.com/all/__linux__/bionic/latest")
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--no-examples", "--ignore-vignettes"), build_args = c('--no-build-vignettes'), error_on = "error")
        shell: Rscript {0}
        env:
          AWS_DEFAULT_REGION: "us-east-2"
          AWS_ACCESS_KEY_ID: "dummy_key"
          AWS_SECRET_ACCESS_KEY: "dummy_secret"
          AWS_SESSION_TOKEN: "dummy_token"
